[feature] Added Composer plugin `prestissimo`
Prestissimo - plugin that downloads Composer packages in parallel to speed up the installation process.
Will be removed right after release of Composer 2.x (parallelism implemented)

Signed-off-by: Tema Smirnov <git.tema@smirnov.one>

diff --git a/dev/Makefile b/dev/Makefile
--- a/dev/Makefile
+++ b/dev/Makefile
@@ -71,6 +71,10 @@ test:
 		echo 'FAIL [Composer]'; \
 		exit 1; \
 	fi
+	@if [[ -z `docker container run --rm $(IMAGE):$(VERSION) composer global show 2> /dev/null | grep '^hirak/prestissimo [0-9][0-9]*\.[0-9][0-9]*'` ]]; then \
+		echo 'FAIL [Composer prestissimo]'; \
+		exit 1; \
+	fi
 	@echo 'OK'
 
 push:
